apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo2-smon
  labels:
    app: demo2-app
  namespace: demo2
spec:
  endpoints:
  - interval: 30s
    port: web
    path: /metrics
  selector:
    matchLabels:
      app: demo2-app
