apiVersion: v1
kind: Service
metadata:
  name: demo-svc
  labels:
    app: demo-app
  namespace: demo
spec:
  selector:
    app: demo-app
  type: NodePort
  ports:
  - name: demo-app-port
    port: 8081
    targetPort: demo-app-port
