---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: demo
spec:
  replicas: 1
  serviceAccountName: prometheus
  serviceMonitorNamespaceSelector:
    matchLabels:
      app: demo-app
  serviceMonitorSelector:
    matchLabels:
      app: demo-app
