apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo-smon
  labels:
    release: prometheus
  namespace: demo
spec:
  endpoints:
  - port: demo-app-port
    path: /metrics
    interval: 15s
  namespaceSelector:
    matchNames:
    - demo
  selector:
    matchLabels:
      release: prometheus
