apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: monitoring
spec:
  replicas: 1
  serviceAccountName: prometheus
  serviceMonitorNamespaceSelector: {}

### Matching Service Monitor Namespace Selector ###
#    matchLabels:
#      app: monitoring

  serviceMonitorSelector: {}

### Matching Service Monitor Selector ###
#    matchLabels:
#      app: monitoring
