apiVersion: v1
kind: Service
metadata:
  name: demo-svc
  labels:
    app: monitoring

### Default labels for Prometheus Grafana stack ###
    #release: prometheus

  namespace: monitoring
spec:
  selector:
    app: monitoring

### Default labels for Prometheus Grafana stack ###
    #release: prometheus

  type: NodePort
  ports:
  - name: demo-app-port
    port: 8081
    targetPort: demo-app-port
