---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: demo
spec:
  selector:
    matchLabels:
      app: demo-app

### Default labels for Prometheus Grafana stack ###
     # release: prometheus

  template:
    metadata:
      labels:
        app: demo-app

### Default labels for Prometheus Grafana stack ###
       # release: prometheus

    spec:
      containers:
      - image: aputra/express-073:latest
        name: express
        ports:
        - name: demo-app-port
          containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 128Mi
