apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo3-app
  labels:
    app: demo3-app
  namespace: demo3
spec:
  selector:
    matchLabels:
      app: demo3-app
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: demo3-app
    spec:
      containers:
      - name: demo3
        image: docker.io/nirvanarsc/my-app
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
