apiVersion: v1
kind: Service
metadata:
  name: demo3-svc
  labels:
    app: demo3-app
  namespace: demo3
spec:
  type: ClusterIP
  selector:
    app: demo3-app
  ports:
    - protocol: TCP
      name: http-traffic
      port: 8080
      targetPort: 8080
