---
 - name: Prometheus And Grafana Stack Setup Play
   hosts: k8smaster
   gather_facts: false
   
   tasks:
     - name: checking Helm tool is installed or not
       shell: whereis helm | egrep -o "/usr/local/bin/helm|/usr/bin/helm"
       register: out
       failed_when: false
       changed_when: false
     
     - name: Installing Helm tool
       shell: |
               yum install wget -y
               wget https://get.helm.sh/helm-v3.8.3-linux-amd64.tar.gz
               tar -zxf helm-v3.8.3-linux-amd64.tar.gz
               mv linux-amd64/helm /usr/local/bin/
       when: "'helm' not in out.stdout"
  
     - debug:
         msg: Already Helm tool is installed
       when: "'helm' in out.stdout"


     - name: Creating new namespace for Prometheus And Grafana Stack
       command: kubectl create ns monitoring

      
     - name: Adding Prometheus repo and updating helm repo
       shell: |
               helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
               helm repo update
               touch /root/pvc-prometheus-grafana.yaml


     - name: Adding PVC for Prometheus and Grafana
       blockinfile:
         dest: /root/pvc-prometheus-grafana.yaml
         block:
               |
                prometheus:
                  prometheusSpec:
                    storageSpec:
                      volumeClaimTemplate:
                        spec:
                          storageClassName: nfs-client
                          accessModes: ["ReadWriteOnce"]
                          resources:
                            requests:
                              storage: 1Gi

                grafana:
                  persistence:
                    type: pvc
                    enabled: true
                    storageClassName: nfs-client
                    accessModes: ["ReadWriteOnce"]
                    size: 1Gi   
     

     - name: Installing Prometheus And Grafana
       shell: |
               helm install prometheus prometheus-community/kube-prometheus-stack -f /root/pvc-prometheus-grafana.yaml --set prometheus.prometheusSpec.serviceMonitorSelectorNilUsesHelmValues=false --set prometheus.prometheusSpec.podMonitorSelectorNilUsesHelmValues=false -n monitoring
   

     - name: Replace Grafana Service ClusterIP To NodePort
       shell: "kubectl get svc prometheus-grafana -n monitoring -o yaml | sed 's/type: ClusterIP/type: NodePort/g' | kubectl replace -f -"

     - name: Replace Promethus-Alertmanager Service ClusterIP To NodePort
       shell: "kubectl get svc prometheus-kube-prometheus-alertmanager -n monitoring -o yaml | sed 's/type: ClusterIP/type: NodePort/g' | kubectl replace -f -"


     - name: Replace Promethus Service ClusterIP To NodePort
       shell: "kubectl get svc prometheus-kube-prometheus-prometheus -n monitoring -o yaml | sed 's/type: ClusterIP/type: NodePort/g' | kubectl replace -f -"


     - name: Verify Installation
       shell: |
               helm list -A
       register: outs
     - debug: var=outs.stdout_lines
