apiVersion: v1
kind: Service
metadata:
  name: demo1-svc
  labels:
    app: demo1-app

### Default labels for Prometheus Grafana stack ###
    #release: prometheus

  namespace: demo1
spec:
  selector:
    app: demo1-app

### Default labels for Prometheus Grafana stack ###
    #release: prometheus

  type: NodePort
  ports:
  - name: demo-app-port
    port: 8081
    targetPort: demo-app-port
