apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo1-smon
  labels:
    app: demo1-app

### Default labels for Prometheus Grafana stack ###
    #release: prometheus

  namespace: demo1
spec:
  endpoints:
  - port: demo-app-port
    path: /metrics
    interval: 15s
  namespaceSelector:
    matchNames:
    - demo1
  selector:
    matchLabels:
      app: demo1-app

### Default labels for Prometheus Grafana stack ###
      #release: prometheus
