---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: http-requests-total-hpa
  namespace: demo
spec:
  scaleTargetRef:
    kind: Deployment
    name: demo-app
  minReplicaCount: 1
  maxReplicaCount: 10
  cooldownPeriod: 30
  pollingInterval: 1
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus-operated.monitoring:9090
        metricName: http_requests_total
        query: |
          sum(http_requests_total)
        threshold: "6"
